name: Frequent Update

on:
  schedule:
    # Запуск каждые 2 часа (00:00, 02:00, 04:00 и т.д.)
    - cron: "0 */2 * * *"
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests PyGithub maxminddb

      - name: Run script
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          cd source && python main.py
